version: "3.9"

services:
  app:
    container_name: bgscoring
    build:
      context: .
      dockerfile: ./compose/local/app/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    command: /start

  db:
    container_name: bgscoring_db
    image: postgres:16.1-alpine3.19
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: bgscoring_redis
    image: redis:7.0.15-alpine3.19
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
