name: Code Quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11"
    - run: pip install --upgrade pip
    - run: pip install "ruff<1" "mypy<2"
    - run: ruff check bgscoring
    - run: mypy bgscoring
